context withoutCancel
teivah/100-go-mistakes pull request #48
Opened 2023-10-06 10:15 UTC by c0dehu1k

Fixes issue-42

2023-10-06 10:32 UTC, teivah requested changes

2023-10-06 10:32 UTC, teivah commented on docs/index.md
> +Note: From Go 1.21, there is a way to create a new context without cancel. WithoutCancel returns a copy of parent that is not canceled when parent is canceled.
Can you please use this note syntax? https://github.com/teivah/100-go-mistakes/blob/master/docs/index.md?plain=1#L282-L284

2023-10-06 10:32 UTC, teivah commented on docs/index.md
> +Note: From Go 1.21, there is a way to create a new context without cancel. WithoutCancel returns a copy of parent that is not canceled when parent is canceled.
WithoutCancel => [`context.WithoutCancel`](https://pkg.go.dev/context#WithoutCancel), please

2023-10-06 10:32 UTC, teivah commented on docs/index.md
> +Read more [here](https://pkg.go.dev/context#WithoutCancel)
Let's remove this line, please (the link will be attached to context.WithoutCancel)

2023-10-09 12:15 UTC, c0dehu1k commented
@teivah Thanks for the comments, I have fixed them all. Please have a look.

2023-10-10 17:12 UTC, teivah approved these changes
Thank you

2023-10-10 17:12 UTC, merged